# GitHub Action for generating a contribution graph with a snake eating your contributions
name: Generate Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} # Uses the repository owner's username by default
          # List of SVG outputs to generate
          # Example: snake.svg?palette=github-dark
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          # GitHub token is required to fetch contribution data
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push SVG
        run: |
          git config --global user.name 'Krishna Kant Singh'
          git config --global user.email 'krishnakantsingh7017@gmail.com'
          git add dist/
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Generate Contribution Snake"
            git push
          fi